.husky/pre-commit, lint-staged.config.js, package-lock.json, package.json, packages/internal/config/config.js, packages/internal/fetch-http/fetch-http.js, packages/internal/fetch-http/fetch-http.test.js, packages/internal/index.js, packages/internal/modules.js, tsconfig.json
This PR will add internal modules which are reusable helper modules that will be used by other modules. This PR will also add DX improvement that relates with type checking
**Changelogs:**
- Added a new fetch HTTP helper module to help interact with the fetch API both in the client and server sides.
- We will add more test cases for fetch HTTP helper in the future
- Added a config module which actually a module to place non-sensitive static configuration for other SDK modules
- Added es2018 and dom lib type definitions inside the tsconfig.json file to help type checking purposes. Dom lib type definitions are important for logic to check or interact with the window/document object
- Added `@types/node` type definition for node.js
- Moved the lint-staged configuration to the separate …
=> Feat: internal module that contains helper functionality and DX improvement

packages/app/init/init.js, packages/app/init/init.test.js
**Description**
Because the return object from `init` module will be used as `eg. initObject` on other modules, for the easier application, we can use [instanceOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof) javascript for checking the condition. However, we need to refactor `init` module code so we can check it with `instanceOf`.
**Implementation**
- I add `initializeConfig` function so the `init` module will return as an object to be able to check with `instanceOf` javascript.
- Erase `name` properties from `init` module return (also omit it on the testing file)
=> Revision: Refactor Init Module To Be Able To Use InstanceOf

packages/stream/end-stream/end-stream.js
This is the implementation of the end stream module based on this issue https://github.com/inlivedev/inlive-js-sdk/issues/6
- This module consists of a function to end / stop a running live stream by hitting the `/streams/{streamId}/end` endpoint.
- The `endStream` function needs two arguments, initialization instance and the config argument where the stream ID will be put.
- Before the function executes an HTTP request to the end endpoint, it will check whether the client state is already running a stream or currently is live.
- After a stream has been successfully ended / stopped. The function will return the latest updated stream data.
- The test file for this module hasn't been created. We will add the test file next time.
=> feat: end stream module

packages/internal/channel/channel.js
This channel module implementation is based on this issue https://github.com/inlivedev/inlive-js-sdk/issues/16. The channel module is responsible to manage the connection between the client and the channel server either using WebSocket or SSE.
How to use this module:
```js
channel.subscribe(streamId)
channel.onMessage((data) => {
// handle message event here
})
channel.onError((event) => {
// handle error
})
channel.unsubscribe()
```
This module is implemented using these patterns:
- [Singleton pattern](https://rajeshnaroth.medium.com/singletons-in-javascript-and-es6-26f276a21df8): the behaviour of this module is a singleton by default which has the advantage of making the value and state always the same when the module is shared and imported into the other modules.
- [Revealing module …
=> feat: internal module - channel

packages/event/event.js, packages/internal/modules.js, packages/internal/webrtc/webrtc.js, packages/stream/modules.js, packages/stream/prepare-stream/prepare-stream.js
This is the prepare stream module based on this issue https://github.com/inlivedev/inlive-js-sdk/issues/6. The module has a function called `prepareStream` which requests a stream preparation and established the Websocket and WebRTC connections to the server.
- The `prepareStream` function mainly handles of the stream preparation, stream initialization, websocket initialization, and webrtc connection establishment.
- If the `prepareStream` function is provided a stream ID that has ended. It will not run and thrown an error.
- This module also requires to input a video element selector which will select a video element which   the SDK can transmit the media track data into
- Besides managing the stream preparation, stream initialization, websocket initialization and webrtc connection …
=> feat: prepare stream module

package-lock.json, package.json, packages/app/init/init.js, packages/index.js, packages/stream/get-stream/get-stream.js, packages/stream/prepare-stream/prepare-stream.js, tsconfig.json
This is a pre-publish PR consisting of configuration setup and fixing some type checking errors before merging to `main` branch and publishing the SDK.
- For the initial publish, we want to go [pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). This SDK will only ship ES modules and currently cannot be `require()`'d using the CommonJS module system. Why ES module? Because ES module is the current JavaScript module standard. This SDK will probably support the CommonJS module in the future. This will be an improvement for the SDK.
- Because we only ship ES modules, we can go build-less for now. Meaning no build process and we will ship the existing modules inside the `packages` directory as they are.
- Inlive JS SDK currently is not stable enough. Expect …
=> feat: pre publish configuration setup and fix type check errors

packages/internal/fetch-http/fetch-http.js
This will fix the these uncaught error on fetch-http module.
1. Fix uncaught error when the content-type is not `application/json` which means the data is probably a string/text.
2. Change checking http status code to use `response.ok` & `response.status` instead.
=> fix: fix uncaught error on fetch-http module

README.md
This PR will fix the wrong method on the readme.md documentation. The wrong method is
`InliveEvent.on` should be changed to `InliveEvent. subscribe `
=> fix: fix doc wrong event module method

packages/app/init/init.js, packages/stream/create-stream/create-stream.js, packages/stream/end-stream/end-stream.js, packages/stream/get-stream/get-stream.js, packages/stream/get-stream/get-stream.test.js, packages/stream/get-streams/get-streams.js, packages/stream/init-stream/init-stream.js, packages/stream/prepare-stream/prepare-stream.js, packages/stream/start-stream/start-stream.js
This PR will allow us to pass the API origin URL and API version to SDK to resolve issue #39 . The API origin and API version will affect all API request base URLs and allow us to test SDK with the local or development version of API.
=> allow to passing origin and api version to SDK

.eslintrc.cjs, package-lock.json, package.json, packages/event/event.js, packages/index.js, packages/internal/channel/channel.js, packages/widget/client/client.js, packages/widget/element/element.js, packages/widget/index.js
This PR will cover the widget module implementation on this issue https://github.com/inlivedev/inlive-js-sdk/issues/41
This PR will introduce a new widget module which enable the developer to develop their own widget component which can communicate to the Inlive [Real-Time Widget API](https://inlive.app/docs/real-time-widget-api/)
The `InliveWidget` module can be imported in the project like this
```js
import { InliveWidget } from '@inlivedev/inlive-js-sdk'
or
import { InliveWidget } from '@inlivedev/inlive-js-sdk/widget'
```
This is the example usage how you can import the widget component already developed in the UI
```html
<viewer-counter-widget></viewer-counter-widget>
<live-chat-widget></live-chat-widget>
<add-to-cart-widget></add-to-cart-widget>
<script type="module">
import { …
```
=> feat: SDK support for widget development

.gitignore, CONTRIBUTING.md, README.md, package-lock.json, package.json, rollup.config.js
Currently, the SDK cannot run independently on the browser. This is because the SDK requires additional dependencies inside the `node_modules` that makes the SDK works properly. The browser in the other hand doesn't understand if the SDK needs those additional dependencies inside the `node_modules`. The browser then throws an error when running the SDK. This can be fixed by running the SDK in an environment that makes the browser understand if the SDK needs those dependencies. However, this approach requires another tool in order to make the SDK work properly.
This PR will solve that issue by implementing a build or compile process on the SDK. This build or compile process is crucial to bundle the SDK into a single file which will include the dependencies needed into that file to make the …
=> feat: bundling the SDK

README.md
This PR will add information in the readme about accessing SDK through CDN links based on issue #28.
- Separate the SDK installation process into two options: install with package manager like NPM and use CDN links available
- Remove information about the coming-soon widget module
You can see the updated readme [here](https://github.com/inlivedev/inlive-js-sdk/blob/doc/sdk-with-cdn/README.md)
=> doc: add information about sdk with cdn links

README.md, packages/stream/create-stream/create-stream.js, packages/stream/fetch-stream/fetch-stream.js, packages/stream/get-streams/get-streams.js
This PR will update the `getStreams` module and readme. This will enable the pagination support on SDK. The pagination options can be set by passing `page` and `pageSize` values on object parameter.
=> feat: enable support for retrieving a list of streams data through pagination

packages/room/peer/peer.js
This PR will fix the issue about remote stream (participant) is not removed from the stream list when the stream tracks receive an `ended` event.
=> fix: remove remote stream from list when the stream tracks receive an `ended` event

packages/room/README.md, packages/room/peer/peer-types.d.ts, packages/room/peer/peer.js, packages/room/stream/stream.js
add new API on stream and peer package so it can be used to animate something on voice detection based on audio volume level. The new API will use like this:
```javascript
peer.addEventListener('voiceactivity',(ev)=>{
// type AudioLevel = {
//   sequence_no: number
//   timestamp: number
//   audio_level: number
// }
// type VoiceActivity = {
//   type: string
//   track_id: string
//   stream_id: string
//   ssrc: number
//   clock_rate: number
//   audio_levels?: AudioLevel[]
// }
console.log(ev.detail.voiceActivity)
})
```
Use peer voice activity event to do manual query on video element and add animation to show the video is the one that currently speaking
or 
```javascript
stream.addEventListener('voiceactivity',(ev)=>{
console.log(ev.detail.audioLevel)
})
``` 
Use stream voice …
=> add voice activity on stream

packages/room/peer/peer.js
Because we switched the codec to VP9 as the default codec. The bitrate can be reduced to 700kbps for webcam streaming based on [this reference](https://livekit.io/webrtc/bitrate-guide). Once this PR merged then we need to rebuild inlive-room to test it.
=> reduce bitrate to optimize bandwidth

packages/index.js, packages/room/README.md, packages/room/bandwidth-controller/bandwidth-controller.js, packages/room/channel/channel-types.d.ts, packages/room/channel/channel.js, packages/room/facade/facade-types.d.ts, packages/room/facade/facade.js, packages/room/index.js, packages/room/peer/peer-types.d.ts, packages/room/peer/peer.js
Based on the [discussion](https://github.com/asumsi/inlive-website/pull/232#discussion_r1386128373), we will change the way developers can get the room event list.
Previously, developers needs to create room object and access the event object
Example:
```js
import { Room } from '@inlivedev/inlive-js-sdk'
const room = Room()
room.event.{EVENT_NAME}
```
With current implementation, we export the event object separately. The sample usage as below.
Example:
```js
import { RoomEvent } from '@inlivedev/inlive-js-sdk'
RoomEvent.{EVENT_NAME}
```
=> fix: separate room event module

packages/room/channel/channel.js, packages/room/peer/peer-types.d.ts, packages/room/peer/peer.js
The ice candidate may arrive earlier before SetRemoteDescription is called because the answer SDP is returned a bit late due to network or other things. The current implementation will just throw away that the candidate which will makes the connection will fail to connect.
The changes will add the candidate to the pending candidate when the remote SDP is not set yet. The pending candidates will be processed after setRemoteCandidate is successfully called.
=> fix add ice candidate before setRemoteDescription

packages/room/config/config.js, packages/room/facade/facade.js, packages/room/peer/peer.js, packages/room/room-types.d.ts
This PR enables audio red by default on SDK, which might add more bitrates on audio sent but it will improve the audio quality on bad network condition. Read more about it [here](https://webrtchacks.com/red-improving-audio-quality-with-redundancy/)
=> add audio red support and enabled by default

packages/room/README.md, packages/room/api/api-types.d.ts, packages/room/api/api.js, packages/room/channel/channel.js, packages/room/facade/facade.js, packages/room/index.js
- Add a new method `room.getMetadata()` to get a specific room metadata.
- Add a new method `room.setMetadata()` to set metadata for a specific room.
- Add a new method `room.deleteMetadata()` to delete a specific room metadata.
- Add a new room event called `RoomEvent.META_CHANGED` is called and user can listen to the event whenever a metadata changes.
- The readme is updated. [See here](https://github.com/inlivedev/inlive-js-sdk/blob/feat/get-set-delete-metadata/packages/room/README.md).
=> feat: get, set, and delete room metadata

.vscode/settings.json, packages/room/README.md, packages/room/api/fetcher.js, packages/room/peer/peer-types.d.ts, packages/room/peer/peer.js
- `peer.addStream()` now asynchronous function to support asynchronous flow when adding local media stream.
- Readme about `peer.addStream()` was updated.
- Revert second parameter type for`peer.addStream()`. Use `AddStreamParameters` instead of `InstanceStream`
- Different fetching error message when no response or content-type is plain/text.
- Remove `STREAM_ADDED` internal-only event.
=> fix: fix type and functionality error after enabling get codec from room api

packages/room/README.md, packages/room/facade/facade.js, packages/room/peer/peer-types.d.ts, packages/room/peer/peer.js
- `room.createPeer()` now accepts a config object as the third parameter. The config object consists of: 
- `codecs`: codecs configurations. The value is the same as `codec_preferences` which is an array of mimetype string. When this codecs configuration not set, the default configuration will be:
- For audio will use `audio/red` first, then continue with `audio/opus`.
- For video will use `video/VP9` first, then put the rest of codecs
- `bitrate`: bitrate object configurations. Consists of three bitrate configurations:
1. maxBitrate: same as `bitrates.video_high` data from room. When not set, the default is 1200 * 1000.
2. midBitrate: same as `bitrates.video_mid` data from room. When not set, the default is 500 * 1000.
3. minBitrate: same as `bitrates.video_low` data from room. When not …
=> feat: enable to set the codec and bitrate preferences

packages/room/peer/peer-types.d.ts, packages/room/peer/peer.js
- Enable to set [scalabilityMode](https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*) through `room.createPeer()` config. When not set, the default value is `L3T1`.
- Enable to set `maxFramerate` through `room.createPeer()` config. When not set, the default value is 30.
- The following `room.createPeer()` config properties will change the name and follow the `rid` high and low configurations. These properties will be used for setting the [maxBitrate](https://docs.w3cub.com/dom/rtcrtpencodingparameters/maxbitrate) for the corresponding rid quality. 
- maxBitrate => highBitrate
- minBitrate => lowBitrate
=> fix: set scalabilityMode and maxFramerate through config and change bitrate config properties

packages/room/peer/peer.js
- Only call [`setCodecPreferences()`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/setCodecPreferences) when the browser supports the method.
- Disable svc setting on firefox because firefox doesn't support svc encoding based on [livekit codecs guide](https://livekit.io/webrtc/codecs-guide).
=> fix: handle unsupported codec and encoding

packages/room/channel/channel.js, packages/room/peer/peer-types.d.ts, packages/room/peer/peer.js
- Fixes the client cannot listen for `allow_negotiation` SSE event because of wrong name. The correct SSE event name is `allowed_renegotation`
- Negotiation is triggered manually without listening the `negotiationneeded` event.
=> fix: event allow_negotiation should be changed to allowed_renegotation

packages/room/observer/video-observer-types.d.ts, packages/room/observer/video-observer.js
This PR should fix the video observer can't send video resized event more than one video element.
=> Fx video resize can't send resize info more than one video

packages/room/api/api.js
Previously `getRoom()` function would get an old room data stored in the variable. This caused the function returns `200` response when the data already exists, not knowing whether the current response is 200, 404, or 500 in the actual endpoint.
=> fix: getRoom() should always returns the response from the api endpoint

packages/room/README.md, packages/room/api/api.js
To use the `createClient()` method, user needs to pass the API key
=> fix: register client require api key

packages/room/api/fetcher.js
The `Content-Type` header was overwritten and removed when `Authorization` header was inputted into the fetcher option. This caused the fetcher would not be able to send body json data using `application/json` Content-Type. This PR fixes this issue
=> fix: Content-Type header was overwritten and removed unexpectedly by other headers input

packages/room/api/api-types.d.ts, packages/room/api/api.js, packages/room/room-types.d.ts
There is a breaking changes API endpoint on room create and get basically both endpoints will have the same endpoint response like this:
```json
{
"id": "string",
"name": "string",
"options": {
"bitrates": {
"audio": 48000,
"audio_red": 75000,
"initial_bandwidth": 1000000,
"video": 1200000,
"video_high": 1200000,
"video_high_pixels": 921600,
"video_low": 150000,
"video_low_pixels": 64800,
"video_mid": 500000,
"video_mid_pixels": 259200
},
"codecs": [
"video/VP9",
"video/H264",
"video/VP8",
"audio/red",
"audio/opus"
],
"empty_room_timeout_ns": 300000000000,
"pli_interval_ns": 0,
"quality_presets": {
"high": {
"sid": 3,
"tid": 3
},
"low": {
"sid": 1,
"tid": 1
},
"mid": {
"sid": 2,
"tid": 2
}
}
}
}
```
This PR also will adapt the response with the SDK room type for example time type in API …
=> adapt with room API endpoints

packages/room/api/api.js
This PR fixes the `options` is undefined which crashed the function when room API returns 404 response and sdk tries to accessing the data inside the `options` object.
The default `getRoom()` response when trying to call 404 room will return option object like this
```js
options: {
bitrates: {
audio: 0,
audioRed: 0,
video: 0,
videoHigh: 0,
videoHighPixels: 0,
videoMid: 0,
videoMidPixels: 0,
videoLow: 0,
videoLowPixels: 0,
initialBandwidth: 0
},
codecs: [],
pliIntervalMS: 0,
emptyRoomTimeoutMS: 0,
qualityPresets: { 
high: {
sid: undefined,
tid: undefined,
}, 
mid:{
sid: undefined,
tid: undefined,
}, 
low:{
sid: undefined,
tid: undefined,
}
}
}
```
=> fix: ensure "options" in the response data is not undefined when getting 404 room not found

packages/room/README.md
This PR adds the configuration section for the `Room()` module initialization in the README. Please see the [preview here](https://github.com/inlivedev/inlive-js-sdk/blob/doc/add-config-options/packages/room/README.md#configurations)
=> docs: add config options information

packages/room/config/config.js, packages/room/peer/peer.js
This PR add bitrate config to create peer function and set the default bitrate to 700kbps as we use VP9 as default bitrate. The default bitrate is taken from config parameter instead of hard coded.
=> add bitrates to config and adjust the default to VP9 bitrates

packages/room/config/config.js
When the bitrate below 900kbps somehow the webrtc always report bandwidth limitation issue. We're adjust this to 900kbps to make sure we don't have that issue.
=> update default bitrate to prevent bandwidth limitation

packages/room/channel/channel.js, packages/room/peer/peer.js, packages/room/stream/streams.js
This PR will fix the issue of a remote stream data with empty client id and empty client name value because of race condition between `track` and `tracks_available` events. The SDK stored a remote stream too early on `track` event when the client ID and client name are still empty because `tracks_available` event was not triggered earlier than `track` event.
When `track` and `tracks_available` events are triggered, we will store the data we needed into a draft stream object. For example, we need a **mediaStream** object when `track` event is triggered, and we need **client ID**, **client Name**, stream **source** (media, screen) and stream **origin** when `tracks_available` event is triggered. Because the data are scattered, we need to combine them into one stream object first. If the …
=> fix: empty string value on remote client id and client name

packages/room/peer/peer.js, packages/room/stream/stream.js
Some changes needed to fix the vad is not trigger and can't be use in inlive-room:
- returned stream object is not freeze to make sure it return the stream event target object, not a static object
- vad is not pass the correct parameter make the stream can't be found to trigger voice activity
=> fix: vad can trigger voice activity

packages/room/README.md, packages/room/index.js, packages/room/peer/peer.js
This PR will add additional behaviour for `turnOnCamera()`, `turnOffCamera()`, `turnOnMic()`, `turnOffMic()` methods.
Previously the behaviour those methods were just toggling the [enabled](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled) property of the video and audio MediaStreamTracks. This would send an empty 0 frame as an output. This worked by muting the audio and making the video blank. However, the camera indicator was still turning on which might made the user concern whether the camera was actually turned off or still turned on.
These are the current behaviour for those methods:
- `peer.turnOnCamera(videoTrack?: MediaStreamTrack | undefined)`
By default when the video track parameter is empty, the method will enable the video track. When the video track …
=> feat: update for on/off camera and mic media input

packages/room/api/auth.js
The fetch request to get the access token should not be stored in any form of cache
=> fix: use no-store cache to prevent storing cache
